services:
  formapp:
    container_name: app_form
    build:
      context: .
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - "4001:80"
    restart: unless-stopped